on:
  push:
    tags:
    - '*'
  pull_request:
    branches:
    - '*'
  workflow_dispatch:
    branches:
    - '*'
  repository_dispatch:
    types: [build]

name: Build IMU-F
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:

    # curl, by default, may timeout easily
    - name: curl fix
      run: function curl () { command curl --connect-timeout 30 --retry 10 "$@" ; }

    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 15

    - name: ARM SDK
      uses: fiam/arm-none-eabi-gcc@master
      with:
        release: '6-2017-q1'

    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Make
      run: ./make.py -T=F3

    - name: Rename Binary
      id: file_version
      run: |
        VER=$(grep FIRMWARE_VERSION ./src/version.h  | awk '{print $3}')
        mv output/F3.bin output/IMUF_${VER}.bin
        echo "::set-output name=VER::${VER}"

    - name: Upload artifcats
      uses: actions/upload-artifact@master
      with:
        name: IMUF_${{steps.file_version.outputs.VER}}
        path: output/*.bin

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:

    - name: Download artifacts
      uses: actions/download-artifact@master

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        generate_release_notes: true
        body: |
          Flash this firmware using the [IMUF Flasher](https://github.com/emuflight/Nemesis/releases/tag/imuf-flasher-0.1.0)
        files: "**/*.bin"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
